### ISSUE TITLE
[MANUAL] Integration Redmine with Authelia

### ISSUE THREAD

**Issue by arbdevml** [devopskube/redmine_openid_connect#79]
Hello. Added a pull request to [the integration with Authelia](https://github.com/devopskube/redmine_openid_connect/pull/78).

https://www.authelia.com/
Authelia is an open-source authentication and authorization server and portal fulfilling the identity and access management (IAM) role of information security in providing multi-factor authentication and single sign-on (SSO) for your applications via a web portal. It acts as a companion for common reverse proxies.

Authelia configuration.yml
Add into the section of "clients"
```
      - id: redmine
        description: Redmine
        secret: '$plaintext$redmine_client_secret'
        public: false
        authorization_policy: one_factor
        redirect_uris:
           - https://redmine.example.com/oic/local_login
        scopes:
           - openid
           - profile
           - groups
           - email
        userinfo_signing_algorithm: none
```

Redmine plugin openID Connect configuration:
**Client ID**: redmine
**OpenID Connect server url**: https://authelia.example.com
**Client Secret**: redmine_client_secret
**OpenID Connect scopes (comma-separated)**: openid,profile,groups,email

**Admins group (members of this group are treated as admin)**: admins

**Disable Ssl Validation**: yes
**Login Selector**: yes
**Create user if not exists**: yes
